stops_to_return: 3

bus:
  gtfs_static_data: "gtfs_m"
  gtfs-rt_urls:
    - "https://gtfsrt.prod.obanyc.com/tripUpdates"
  stops:
    "1 AV/E 57 ST":
      "time_to_stop": 300
    "3 AV/E 57 ST":
      "time_to_stop": 300

subway:
  gtfs_static_data: "gtfs_subway"
  gtfs-rt_urls:
    - "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace"
  stops:
    "Lexington Av/53 St":
      "time_to_stop": 300